[pytest]
addopts =
    -v
    --tb=short
    --strict-markers
    --alluredir=allure-results
    --build-version=6.5.0.9142
    --db-name=TRBOnet_63_autotest
    --zip-path=\\\\nsshare.trbonet.com\\Share\\Tester_common\\bd_for_test\\!bd_migration\\bd_6.3.0\\TRBOnet_6.3.0.bak.zip
    --sql-server=S0343\\SQLEXPRESS
    --sql-user=sa
    --sql-password=trbonet.com
    --data-path=C:\\Database_Backups
    --auth-type=sql
    --uninstall-mode=auto
    --db-restore-timeout=3600
    --db-upgrade-timeout=1800

markers =
    smoke: Тесты для проверки основных функций
    regression: Регрессионные тесты
    installation: Тесты установки
    migration: Тесты миграции
    slow: Медленные тесты
    timeout: Тесты с ограничением по времени выполнения
    dependency: Тесты с зависимостями между собой (pytest-dependency)